apiVersion: batch/v1
kind: CronJob
metadata:
  name: cjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: busybox
              image: busybox:1.28
              command: ["sh", "-c"]
              args:
                - date
          restartPolicy: OnFailure