apiVersion: batch/v1
kind: Job
metadata:
  name: cjob-manual
spec:
  template:
    spec:
      containers:
        - name: busybox
          image: busybox:1.28
          command: ["sh", "-c"]
          args:
            - date
      restartPolicy: OnFailure
