apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  labels:
    app: backend-service
    tier: backend-service
spec:
  type: ClusterIP
  selector:
    app: backend-server
    tier: backend
  ports:
    - port: 80
      targetPort: 80
