apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgsql-pvclaim
  labels:
    app: pgsql-pvc
    tier: storage
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  